name: Pipeline Estudo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Teste
      run: coverage run app_test.py

    - name: Relatorio do Teste
      run: coverage report -m

    - name: AWS Deploy
      run: |
            echo "Conectando"
            echo "${{secrets.AWS_KEY}}" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-174-129-149-160.compute-1.amazonaws.com "
                   cd Flask-Pratica/;git pull;./executar.sh"

    # - name: Render Deploy Action
    #   # You may pin to the exact commit or the version.
    #   # uses: johnbeynon/render-deploy-action@a0588f9aca995a15d69a72cb2bfbf37c12e5b540
    #   uses: johnbeynon/render-deploy-action@v0.0.8
    #   with:
    #     # ID of the service to deploy
    #     service-id: 
    #     # A Render API key
    #     api-key:
